services:
  mariadb:
    image: mariadb:lts
    container_name: project_ms_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT_DOCKER}"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      timeout: 15s
      interval: 5s
      retries: 5
      start_period: 30s




  pm_server:
    container_name: project_ms_server_container
    build: ./server
    image: project_ms_server:v2
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT_DOCKER}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - DB_CONNECTION_LIMIT=${DB_CONNECTION_LIMIT}
    - SERVER_PORT=${SERVER_PORT}
    - NODE_ENV=${NODE_ENV}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - internalnet

  pm_frontend:
    container_name: project_ms_frontend_container
    build: ./frontend
    image: project_ms_frontend:v2
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - pm_server
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_NODE_ENV=${VITE_NODE_ENV}
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
volumes:
  mariadb_data: