services:
  mariadb:
    image: mariadb:lts
    container_name: project_ms_dev_db
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - project_ms_db_dev_data:/var/lib/mysql
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT_DOCKER}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: development
      SERVICE_NAME: project_ms_dev_db
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      timeout: 15s
      interval: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8-alpine
    container_name: project_ms_redis_dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - internalnet

  pm_server_dev:
    container_name: pm_server_dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: pm_server_dev:dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: mariadb
      DB_PASSWORD: 'pwd@123'
      DB_USER: admin
      DB_NAME: project_ms
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_CONNECTION_LIMIT: 10
      NODE_ENV: development
      SERVER_PORT: 8000
      SERVICE_TAGS: development
      SERVICE_NAME: pm_server_devservice
    volumes:
      # Mount source code for hot reload
      - ./server:/app/server
      - /app/server/node_modules  # Prevent overwriting node_modules
    networks:
      - internalnet

  pm_frontend_dev:
    container_name: pm_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Use development Dockerfile
    image: pm_frontend_dev:dev
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - pm_server_dev
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_NODE_ENV=${VITE_NODE_ENV}
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app/frontend
      - /app/frontend/node_modules  # Prevent overwriting node_modules
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  project_ms_db_dev_data:
  redis_data: