services:
  mariadb:
    image: mariadb:lts
    container_name: project_ms_db
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: project_ms
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd@123
      MYSQL_ROOT_PASSWORD: pwd@123
      SERVICE_TAGS: prod
      SERVICE_NAME: project_ms_db
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-ppwd@123"]
      timeout: 5s
      retries: 10


  redis:
    image: redis:8-alpine
    container_name: project_ms_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - internalnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 3s
      retries: 5
      interval: 5s

  pm_server:
    container_name: project_ms_server_container
    build: ./server
    image: project_ms_server:v2
    ports:
      - 8081:8080
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: mariadb
      DB_PASSWORD: 'pwd@123'
      DB_USER: admin
      DB_NAME: project_ms
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_CONNECTION_LIMIT: 10
      NODE_ENV: production
      SERVICE_TAGS: prod
      SERVICE_NAME: project_ms_server_service
    networks:
      - internalnet

  pm_frontend:
    container_name: project_ms_frontend_container
    build: ./frontend
    image: project_ms_frontend:v2
    ports:
      - 5000:5000
    depends_on:
      - pm_server
    environment:
      VITE_APP_SERVER_URL: http://pm_server:8080
      NODE_ENV: production
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge