name: Feature request
description: Have an idea or feature request? Let us know!
labels: type: feature
body:
  - type: textarea
    id: idea
    attributes:
      label: What is your feature idea and why it should be implemented?
    validations:
      required: true

  - type: textarea
    id: optional
    attributes:
      label: Additional context
    validations:
      required: false
