# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: quay.io/srntp/project-ms-server:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: logs-volume
              mountPath: /app/server/logs
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_name
            - name: DB_PORT
              value: "3306"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: DB_CONNECTION_LIMIT
              value: "100"
            - name: SERVER_PORT
              value: "8000"
            - name: NODE_ENV
              value: production
            - name: IS_DOCKER
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: server